// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn4UDw2J8PAm7RekcixLqNCWwH3SynEPs',
    appId: '1:913936210266:web:7dc9581c3ed4dc4308fb63',
    messagingSenderId: '913936210266',
    projectId: 'pizza-opole',
    authDomain: 'pizza-opole.firebaseapp.com',
    storageBucket: 'pizza-opole.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDmqfHxaa_IJGcG1fBNO8TdTdEjrtfh-c',
    appId: '1:913936210266:android:77ee81fe5dea255108fb63',
    messagingSenderId: '913936210266',
    projectId: 'pizza-opole',
    storageBucket: 'pizza-opole.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMi8vagZZUaLMbBnX9ryDHNO8lj9Tm_BQ',
    appId: '1:913936210266:ios:195392041e40b1a108fb63',
    messagingSenderId: '913936210266',
    projectId: 'pizza-opole',
    storageBucket: 'pizza-opole.appspot.com',
    iosClientId: '913936210266-9shhipag415oielstj0unslpc1eoc8f4.apps.googleusercontent.com',
    iosBundleId: 'com.wiktoriaholm.pizzaOpole',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMi8vagZZUaLMbBnX9ryDHNO8lj9Tm_BQ',
    appId: '1:913936210266:ios:195392041e40b1a108fb63',
    messagingSenderId: '913936210266',
    projectId: 'pizza-opole',
    storageBucket: 'pizza-opole.appspot.com',
    iosClientId: '913936210266-9shhipag415oielstj0unslpc1eoc8f4.apps.googleusercontent.com',
    iosBundleId: 'com.wiktoriaholm.pizzaOpole',
  );
}
